apiVerison: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: github-action-gcr@prod1-415815.iam.gserviceaccount.com:matchmate/frontend
    targetRevision: HEAD
    path: infra/frontend.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: matchmate
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      prune: true
      selfHeal: true


