name: Build 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  


permissions: 
  contents: read
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build Docker image
        working-directory: ./frontend
        run: |
          docker build -t my-image .

      - name: Google Artifact Registry Build & Push
        uses: piotr-krusinski/action-google-artifact-registry@v1.0
        with:
          google_project_id: prod1-415815
          google_artifact_registry_region: europe-west1
          google_artifact_registry_hostname: eu.artifacts.prod1-415815.appspot.com
          google_artifact_registry_name: frontend-argocd
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          dockerfile: ./frontend/Dockerfile
          image_name: frontend-argocd
          tag_list: version_1.0 master 
          build_args: docker build args
          






















      # - name: Install and Build Express Server
      #   working-directory: ./backend
      #   run: |
      #     npm ci
      #     npm run test
      #   env:
      #     CLIENT_URL: ${{secrets.CLIENT_URL}}
      #     MYSQL_DB: ${{secrets.MYSQL_DB}}
      #     MYSQL_PORT: ${{secrets.MYSQL_PORT}}
      #     MYSQL_CLOUD_USER: ${{secrets.MYSQL_CLOUD_USER}}
      #     MYSQL_CLOUD_PASS: ${{secrets.MYSQL_CLOUD_PASS}}
      #     MYSQL_CLOUD_HOST: ${{secrets.MYSQL_CLOUD_HOST}}
      #     ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
      #     REFRESH_TOKEN_SECRET: ${{secrets.REFRESH_TOKEN_SECRET}}
      #     BUCKET_NAME: ${{secrets.BUCKET_NAME}}
      #     BUCKET_REGION: ${{secrets.BUCKET_REGION}}
      #     BUCKET_ACCESS_KEY: ${{secrets.BUCKET_ACCESS_KEY}}
      #     BUCKET_SECRET_ACCESS_KEY: ${{secrets.BUCKET_SECRET_ACCESS_KEY}}
      #     CLOUDFRONT_DISTRIBUTION_ID: ${{secrets.CLOUDFRONT_DISTRIBUTION_ID}}
      #     CLOUDFRONT_KEY_PAIR_ID: ${{secrets.CLOUDFRONT_KEY_PAIR_ID}}
      #     CLOUDFRONT_URL: ${{secrets.CLOUDFRONT_URL}}
      #     SECRET_REGION: ${{secrets.SECRET_REGION}}
      #     SECRET_SIGNING_KEY: ${{secrets.SECRET_SIGNING_KEY}}
      #     AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      #     AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      #     TEST_USERNAME: ${{secrets.TEST_USERNAME}}
      #     TEST_PASSWORD: ${{secrets.TEST_PASSWORD}}
