name: Build and Push to Google Artifact Registry

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Google Artifact Registry
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          credentials: ${{ secrets.GOOGLE_SA_KEY }}
          scopes: https://www.googleapis.com/auth/cloud-platform
      - name: Build and push Docker image
        working-directory: ./frontend
        run: |
          docker build -t gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.REGISTRY_NAME }}:${{ github.sha }} .
          docker push gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.REGISTRY_NAME }}:${{ github.sha }}




















      # - name: Install and Build Express Server
      #   working-directory: ./backend
      #   run: |
      #     npm ci
      #     npm run test
      #   env:
      #     CLIENT_URL: ${{secrets.CLIENT_URL}}
      #     MYSQL_DB: ${{secrets.MYSQL_DB}}
      #     MYSQL_PORT: ${{secrets.MYSQL_PORT}}
      #     MYSQL_CLOUD_USER: ${{secrets.MYSQL_CLOUD_USER}}
      #     MYSQL_CLOUD_PASS: ${{secrets.MYSQL_CLOUD_PASS}}
      #     MYSQL_CLOUD_HOST: ${{secrets.MYSQL_CLOUD_HOST}}
      #     ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
      #     REFRESH_TOKEN_SECRET: ${{secrets.REFRESH_TOKEN_SECRET}}
      #     BUCKET_NAME: ${{secrets.BUCKET_NAME}}
      #     BUCKET_REGION: ${{secrets.BUCKET_REGION}}
      #     BUCKET_ACCESS_KEY: ${{secrets.BUCKET_ACCESS_KEY}}
      #     BUCKET_SECRET_ACCESS_KEY: ${{secrets.BUCKET_SECRET_ACCESS_KEY}}
      #     CLOUDFRONT_DISTRIBUTION_ID: ${{secrets.CLOUDFRONT_DISTRIBUTION_ID}}
      #     CLOUDFRONT_KEY_PAIR_ID: ${{secrets.CLOUDFRONT_KEY_PAIR_ID}}
      #     CLOUDFRONT_URL: ${{secrets.CLOUDFRONT_URL}}
      #     SECRET_REGION: ${{secrets.SECRET_REGION}}
      #     SECRET_SIGNING_KEY: ${{secrets.SECRET_SIGNING_KEY}}
      #     AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      #     AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      #     TEST_USERNAME: ${{secrets.TEST_USERNAME}}
      #     TEST_PASSWORD: ${{secrets.TEST_PASSWORD}}
