name: Build and Push Docker Image

on:
  push:
    branches: [  ]

jobs:
  build-push-dockerhub:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USER}}
      DOCKER_PAT: ${{secrets.DOCKER_AUTH}}  
      IMAGE: frontend-argocd
      TAG: ${{github.sha}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_AUTH }}  

      - name: Build and Push Docker Image
        working-directory: ./frontend
        run: |
          docker build -t $DOCKER_USERNAME/$IMAGE:$TAG .  
          docker push $DOCKER_USERNAME/$IMAGE:$TAG
