name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Google Container Registry
      uses: docker/login-action@v1 
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GOOGLE_SA_KEY }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        file: ./frontend/Dockerfile
        push: true
        tags: gcr.io/${{ secrets.GCR_PROJECT_ID }}/frontend-argocd:latest












      # - name: Install and Build Express Server
      #   working-directory: ./backend
      #   run: |
      #     npm ci
      #     npm run test
      #   env:
      #     CLIENT_URL: ${{secrets.CLIENT_URL}}
      #     MYSQL_DB: ${{secrets.MYSQL_DB}}
      #     MYSQL_PORT: ${{secrets.MYSQL_PORT}}
      #     MYSQL_CLOUD_USER: ${{secrets.MYSQL_CLOUD_USER}}
      #     MYSQL_CLOUD_PASS: ${{secrets.MYSQL_CLOUD_PASS}}
      #     MYSQL_CLOUD_HOST: ${{secrets.MYSQL_CLOUD_HOST}}
      #     ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
      #     REFRESH_TOKEN_SECRET: ${{secrets.REFRESH_TOKEN_SECRET}}
      #     BUCKET_NAME: ${{secrets.BUCKET_NAME}}
      #     BUCKET_REGION: ${{secrets.BUCKET_REGION}}
      #     BUCKET_ACCESS_KEY: ${{secrets.BUCKET_ACCESS_KEY}}
      #     BUCKET_SECRET_ACCESS_KEY: ${{secrets.BUCKET_SECRET_ACCESS_KEY}}
      #     CLOUDFRONT_DISTRIBUTION_ID: ${{secrets.CLOUDFRONT_DISTRIBUTION_ID}}
      #     CLOUDFRONT_KEY_PAIR_ID: ${{secrets.CLOUDFRONT_KEY_PAIR_ID}}
      #     CLOUDFRONT_URL: ${{secrets.CLOUDFRONT_URL}}
      #     SECRET_REGION: ${{secrets.SECRET_REGION}}
      #     SECRET_SIGNING_KEY: ${{secrets.SECRET_SIGNING_KEY}}
      #     AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      #     AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      #     TEST_USERNAME: ${{secrets.TEST_USERNAME}}
      #     TEST_PASSWORD: ${{secrets.TEST_PASSWORD}}
